name: freedom
description: Your all in one ride and delivery service
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  dio: ^5.7.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  get_it: ^8.0.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  retrofit: ^4.4.1
  shared_preferences: ^2.3.2
dev_dependencies:
  bloc_test: ^9.1.7
  retrofit_generator: ^9.1.3
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
